import os
import sqlite3
from datetime import datetime, timezone
from pathlib import Path


class PostgresConnection:
    """Adapt Hush's fixed SQL queries; values stay parameterized.

    These queries must not contain literal question marks or percent signs.
    """
    def __init__(self, connection):
        self.connection = connection

    def execute(self, query, params=None):
        return self.connection.execute(query.replace("?", "%s"), params)

    def commit(self):
        self.connection.commit()

    def rollback(self):
        self.connection.rollback()

    def close(self):
        self.connection.close()


def _postgres_row(cursor):
    # Preserve the existing API's UTC strings for the room's timestamp display.
    columns = [column.name for column in cursor.description] if cursor.description else []

    def make_row(values):
        result = dict(zip(columns, values))
        for key, value in result.items():
            if isinstance(value, datetime):
                if value.tzinfo is not None:
                    value = value.astimezone(timezone.utc).replace(tzinfo=None)
                result[key] = value.isoformat(sep=" ")
        return result

    return make_row

def get_db():
    database_url = os.environ.get("DATABASE_URL", "").strip()
    if database_url:
        if not database_url.startswith(("postgresql://", "postgres://")):
            raise RuntimeError("DATABASE_URL must be a PostgreSQL connection URL")
        import psycopg

        try:
            conn = psycopg.connect(
                database_url, row_factory=_postgres_row,
                sslmode="require", connect_timeout=10,
                options="-c timezone=UTC",
            )
        except psycopg.OperationalError:
            # Avoid exposing the URL/password or silently reverting to SQLite.
            raise RuntimeError(
                "PostgreSQL connection failed. Check DATABASE_URL and network access."
            ) from None
        return PostgresConnection(conn)

    path = os.environ.get("SQLITE_PATH") or str(Path(__file__).with_name("hush.db"))
    conn = sqlite3.connect(path)
    conn.row_factory = sqlite3.Row
    return conn

def init_db():
    conn = get_db()
    try:
        _create_tables(conn)
        conn.commit()
    except Exception:
        conn.rollback()
        raise
    finally:
        conn.close()


def _create_tables(conn):
    class SchemaCursor:
        def execute(self, statement):
            if isinstance(conn, PostgresConnection):
                statement = statement.replace(
                    "INTEGER PRIMARY KEY AUTOINCREMENT",
                    "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
                )
            return conn.execute(statement)

    cursor = SchemaCursor()

    # users table — username + password hash + their anonymous ID
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS users (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            username TEXT UNIQUE NOT NULL,
            password_hash TEXT NOT NULL,
            anon_id TEXT NOT NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
    """)

    # moods — stored under anon_id, not username
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS moods (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            user_id TEXT,
            mood TEXT,
            note TEXT,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
    """)

    # messages — stored under anon_id
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS messages (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            user_id TEXT,
            role TEXT,
            content TEXT,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
    """)
    cursor.execute("""
    CREATE TABLE IF NOT EXISTS room_messages (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        room TEXT,
        user_id TEXT,
        label TEXT,
        content TEXT,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
""")
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS doctor_requests (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            user_id TEXT,
            mood_summary TEXT,
            message TEXT,
            status TEXT DEFAULT 'pending',
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
    """)
