"""Run with python -m unittest test_database; never uses the real database."""
import os
import tempfile
import unittest
from datetime import datetime, timezone
from pathlib import Path
from types import SimpleNamespace
from unittest.mock import Mock, patch

import database


class DatabaseTests(unittest.TestCase):
    def setUp(self):
        self.temp = tempfile.TemporaryDirectory()
        self.env = patch.dict(os.environ, {
            "DATABASE_URL": "", "SQLITE_PATH": str(Path(self.temp.name) / "test.db"),
            "PYTHON_DOTENV_DISABLED": "1",
        })
        self.env.start()

    def tearDown(self):
        self.env.stop()
        self.temp.cleanup()

    def test_schema_is_repeatable_and_preserves_rows(self):
        database.init_db()
        conn = database.get_db()
        conn.execute("INSERT INTO users (username, password_hash, anon_id) VALUES (?, ?, ?)",
                     ("tester", "hash", "anon"))
        conn.commit()
        conn.close()
        database.init_db()
        conn = database.get_db()
        self.assertEqual(conn.execute("SELECT username FROM users").fetchone()["username"], "tester")
        tables = {r["name"] for r in conn.execute("SELECT name FROM sqlite_master WHERE type='table'").fetchall()}
        self.assertTrue({"users", "moods", "messages", "room_messages", "doctor_requests"} <= tables)
        conn.close()

    def test_account_and_private_mood_flows(self):
        import app
        database.init_db()
        app.app.config["TESTING"] = True
        client = app.app.test_client()
        form = {"username": "alice", "password": "test-password", "confirm_password": "test-password"}
        self.assertEqual(client.post("/register", data=form).status_code, 302)
        self.assertEqual(client.post("/api/mood", json={"mood": "okay", "note": "test"}).status_code, 200)
        self.assertEqual(len(client.get("/api/mood/history").get_json()), 1)
        self.assertEqual(client.post("/api/doctor/request", json={"message": "test request"}).status_code, 503)
        client.get("/logout")
        self.assertEqual(client.get("/api/mood/history").status_code, 302)
        self.assertIn(b"wrong username", client.post("/login", data={"username": "alice", "password": "wrong"}).data)
        self.assertEqual(client.post("/login", data=form).status_code, 302)
        client.get("/logout")
        form["username"] = "bob"
        client.post("/register", data=form)
        self.assertEqual(client.get("/api/mood/history").get_json(), [])
        self.assertIn(b"already taken", client.post("/register", data=form).data)

    def test_postgres_configuration_and_bound_values(self):
        import psycopg
        raw = Mock()
        with patch.dict(os.environ, {"DATABASE_URL": "postgresql://example.invalid/hush"}), patch.object(psycopg, "connect", return_value=raw) as connect:
            conn = database.get_db()
            value = "quote' ? 100%"
            conn.execute("SELECT * FROM users WHERE username = ?", (value,))
            raw.execute.assert_called_once_with("SELECT * FROM users WHERE username = %s", (value,))
            self.assertEqual(connect.call_args.kwargs["sslmode"], "require")
            self.assertEqual(connect.call_args.kwargs["connect_timeout"], 10)

    def test_postgres_failure_does_not_fall_back_or_expose_password(self):
        import psycopg
        with patch.dict(os.environ, {"DATABASE_URL": "postgresql://user:secret@example.invalid/hush"}), patch.object(psycopg, "connect", side_effect=psycopg.OperationalError("secret")):
            with self.assertRaises(RuntimeError) as result:
                database.get_db()
            self.assertNotIn("secret", str(result.exception))
            self.assertFalse(Path(os.environ["SQLITE_PATH"]).exists())

    def test_postgres_schema_uses_identity_columns(self):
        raw = Mock()
        with patch.object(database, "get_db", return_value=database.PostgresConnection(raw)):
            database.init_db()
        statements = [call.args[0] for call in raw.execute.call_args_list]
        self.assertEqual(len(statements), 5)
        self.assertTrue(all("GENERATED BY DEFAULT AS IDENTITY" in sql for sql in statements))
        self.assertTrue(all("AUTOINCREMENT" not in sql for sql in statements))
        raw.commit.assert_called_once()
        raw.close.assert_called_once()

    def test_postgres_timestamps_preserve_browser_format(self):
        cursor = SimpleNamespace(description=[SimpleNamespace(name="created_at")])
        row = database._postgres_row(cursor)([datetime(2026, 9, 30, 12, 30, tzinfo=timezone.utc)])
        self.assertEqual(row["created_at"], "2026-09-30 12:30:00")

    def test_invalid_database_url_is_rejected(self):
        with patch.dict(os.environ, {"DATABASE_URL": "https://example.invalid"}):
            with self.assertRaises(RuntimeError):
                database.get_db()

    def test_deletion_is_scoped_and_requires_csrf(self):
        import app
        database.init_db()
        conn = database.get_db()
        for user in ("alice", "bob"):
            conn.execute("INSERT INTO moods (user_id, mood, note) VALUES (?, ?, ?)", (user, "okay", "private note"))
        conn.commit()
        conn.close()
        client = app.app.test_client()
        self.assertEqual(client.post("/mood/history/delete").status_code, 302)
        with client.session_transaction() as state:
            state["user_id"] = "alice"
        page = client.get("/dashboard")
        self.assertIn(b"Delete my mood history", page.data)
        with client.session_transaction() as state:
            token = state["mood_delete_token"]
        self.assertEqual(client.get("/mood/history/delete").status_code, 405)
        self.assertEqual(client.post("/mood/history/delete", data={"csrf_token": "wrong", "user_id": "bob"}).status_code, 403)
        conn = database.get_db()
        self.assertEqual(len(conn.execute("SELECT * FROM moods").fetchall()), 2)
        conn.close()
        self.assertEqual(client.post("/mood/history/delete", data={"csrf_token": token, "user_id": "bob"}).status_code, 302)
        conn = database.get_db()
        rows = conn.execute("SELECT user_id FROM moods").fetchall()
        self.assertEqual([row["user_id"] for row in rows], ["bob"])
        conn.close()
        self.assertEqual(client.post("/mood/history/delete", data={"csrf_token": token}).status_code, 403)

    def test_chat_replies_without_saving_new_messages(self):
        import app
        import urllib.request
        database.init_db()
        conn = database.get_db()
        conn.execute("INSERT INTO messages (user_id, role, content) VALUES (?, ?, ?)", ("alice", "user", "older saved chat"))
        conn.commit()
        conn.close()
        client = app.app.test_client()
        with client.session_transaction() as state:
            state["user_id"] = "alice"
        response = Mock()
        response.__enter__ = Mock(return_value=response)
        response.__exit__ = Mock(return_value=False)
        response.read.return_value = b'{"choices":[{"message":{"content":"test reply"}}]}'
        with patch.object(urllib.request, "urlopen", return_value=response):
            result = client.post("/api/chat", json={"messages": [{"role": "user", "content": "new private chat"}]})
        self.assertEqual(result.get_json()["reply"], "test reply")
        conn = database.get_db()
        rows = conn.execute("SELECT content FROM messages").fetchall()
        self.assertEqual([row["content"] for row in rows], ["older saved chat"])
        conn.close()

    def test_old_public_secret_cannot_sign_in(self):
        import app
        from flask import Flask
        from itsdangerous import BadSignature
        old_app = Flask("old")
        old_app.secret_key = "hush-secret-key"
        old_serializer = old_app.session_interface.get_signing_serializer(old_app)
        forged = old_serializer.dumps({"user_id": "alice"})
        new_serializer = app.app.session_interface.get_signing_serializer(app.app)
        with self.assertRaises(BadSignature):
            new_serializer.loads(forged)
        self.assertEqual(app.app.config["SESSION_COOKIE_SAMESITE"], "Lax")
        self.assertTrue(app.app.config["SESSION_COOKIE_HTTPONLY"])
        page = app.app.test_client().get("/privacy")
        self.assertEqual(page.status_code, 200)
        self.assertIn(b"administrators can access", page.data)


if __name__ == "__main__":
    unittest.main()
