const assert = require('node:assert/strict');
const {GroundingMoment} = require('./static/grounding.js');
const moment = new GroundingMoment();
for (let i=0;i<30;i++) moment.alternate();
assert.equal(moment.promptIndex,0);
moment.resting=true;
assert.equal(moment.notice(),false);
moment.alternate();
assert.equal(moment.promptIndex,0);
moment.resting=false;
moment.alternate();
assert.equal(moment.promptIndex,1);
assert.equal(moment.notice(),true);
assert.equal(moment.promptIndex,2);
assert.equal(moment.notice(),true);
assert.equal(moment.promptIndex,0);
assert.equal(moment.notice(),true);
assert.equal(moment.complete,true);
assert.equal(moment.notice(),false);
moment.alternate();
assert.equal(moment.promptIndex,1);
console.log('Grounding checks passed: skipped prompts advance correctly, pause blocks progress, completion is bounded.');
